"""Initial migration

Revision ID: 10a371048e22
Revises: 
Create Date: 2025-04-20 22:40:14.204934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a371048e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_application', ['student_id', 'company_id'])

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visit_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('visit_date')
        batch_op.drop_column('description')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint('unique_application', type_='unique')

    # ### end Alembic commands ###
