"""Added is_placed column to StudentProfile

Revision ID: 872c58402ce1
Revises: 10a371048e22
Create Date: 2025-04-21 01:09:22.974825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872c58402ce1'
down_revision = '10a371048e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_placed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_column('is_placed')

    # ### end Alembic commands ###
